### ISSUE TITLE
[BUG] Incompatibility with python 3.11

### ISSUE THREAD

**Issue by LucileNaegele** [DeMarcoLab/fibsem#194]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lnae0002\AppData\Local\miniconda3\envs\tescan11\Scripts\fibsem_ui.exe\__main__.py", line 4, in <module>
  File "C:\Users\lnae0002\Desktop\fibsem\fibsem\ui\FibsemUI.py", line 6, in <module>
    from fibsem import utils
  File "C:\Users\lnae0002\Desktop\fibsem\fibsem\utils.py", line 14, in <module>
    from fibsem.structures import (
  File "C:\Users\lnae0002\Desktop\fibsem\fibsem\structures.py", line 745, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\lnae0002\AppData\Local\miniconda3\envs\tescan11\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\lnae0002\AppData\Local\miniconda3\envs\tescan11\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lnae0002\AppData\Local\miniconda3\envs\tescan11\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lnae0002\AppData\Local\miniconda3\envs\tescan11\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fibsem.structures.FibsemStagePosition'> for field absolute_position is not allowed: use default_factory

**Comment by patrickcleeve2** [comment]
@schoyo thoughts?

**Comment by patrickcleeve2** [comment]
fixed in: 6e9b26bebcae9695c769d1e33a27583e7b2e066b
