### ISSUE TITLE
Bug in send_email

### ISSUE THREAD

**Issue by GenevieveBuckley** [DeMarcoLab/fibsem#61]
Observed this message - possibly because I haven't set up the system environment variables on the computer downstairs.

```
Do you want to mill all samples? yes/no
yes
2019-06-23 18:26:02,949 Sample 0
Creating milling ROIs...
2019-06-23 18:26:10,121 Ion beam milling in progress, this may take some time...

2019-06-23 18:26:10,122 Sample stage position: StagePosition(x=-0.015999708,y=0.
048999542,z=0.022999518,t=7.80505e-07,r=5.0613942)
2019-06-23 18:26:10,123 Sample 1
Creating milling ROIs...
2019-06-23 18:26:17,926 Ion beam milling in progress, this may take some time...

2019-06-23 18:26:17,926 Sample stage position: StagePosition(x=-0.015999708,y=0.
048999542,z=0.022999518,t=7.80505e-07,r=5.0613942)
2019-06-23 18:26:17,927 Sample 2
Creating milling ROIs...
2019-06-23 18:26:25,075 Ion beam milling in progress, this may take some time...

2019-06-23 18:26:25,075 Sample stage position: StagePosition(x=-0.015999708,y=0.
048999542,z=0.022999518,t=7.80505e-07,r=5.0613942)
2019-06-23 18:26:25,077 All ion beam milling complete.
2019-06-23 18:26:28,266 Uncaught exception <class 'smtplib.SMTPResponseException
'> (334, b'UGFzc3dvcmQ6')
NoneType: None
2019-06-23 18:26:28,269 Traceback (most recent call last):
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\send_email.py", line
35, in send_email
    os.environ.get('FIBSEM_EMAIL_KEY'))
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 721, in login

    initial_response_ok=initial_response_ok)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 638, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\runpy.py", line 193, in _run_mo
dule_as_main
    "__main__", mod_spec)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\runpy.py", line 85, in _run_cod
e
    exec(code, run_globals)
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\main.py", line 29, in
 <module>
    run_milling(host=args.host, config=args.config)
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\main.py", line 23, in
 run_milling
    attachment_filename=log_filename
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\send_email.py", line
37, in send_email
    receiver_email, text)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 280, in __exi
t__
    raise SMTPResponseException(code, message)
smtplib.SMTPResponseException: (334, b'UGFzc3dvcmQ6')
NoneType: None
Error in sys.excepthook:
Traceback (most recent call last):
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\send_email.py", line
35, in send_email
    os.environ.get('FIBSEM_EMAIL_KEY'))
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 721, in login

    initial_response_ok=initial_response_ok)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 638, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 280, in __exi
t__
    raise SMTPResponseException(code, message)
smtplib.SMTPResponseException: (334, b'UGFzc3dvcmQ6')

Original exception was:
Traceback (most recent call last):
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\send_email.py", line
35, in send_email
    os.environ.get('FIBSEM_EMAIL_KEY'))
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 721, in login

    initial_response_ok=initial_response_ok)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 638, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\runpy.py", line 193, in _run_mo
dule_as_main
    "__main__", mod_spec)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\runpy.py", line 85, in _run_cod
e
    exec(code, run_globals)
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\main.py", line 29, in
 <module>
    run_milling(host=args.host, config=args.config)
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\main.py", line 23, in
 run_milling
    attachment_filename=log_filename
  File "c:\users\admin\microscope\demarcolab\fibsem\fibsem\send_email.py", line
37, in send_email
    receiver_email, text)
  File "C:\Users\Admin\Anaconda3\envs\fibsem\lib\smtplib.py", line 280, in __exi
t__
    raise SMTPResponseException(code, message)
smtplib.SMTPResponseException: (334, b'UGFzc3dvcmQ6')

C:\Users\Admin>
```

**Comment by GenevieveBuckley** [comment]
Have investigated and yes, this only happened because the system environment variables `FIBSEM_EMAIL_ADDRESS` and `FIBSEM_EMAIL_KEY` were not set on the lab machine. Everything works well now this is done.
