### ISSUE TITLE
BUG: crash caused if no right click after manual segmentation

### ISSUE THREAD

**Issue by GenevieveBuckley** [DeMarcoLab/fibsem#9]
If the users forgets to right click after drawing a polygon with the manual segmentation, then the script crashes ungracefully.

Better behaviour would be to check whether the mask image is None, and if not just skip the next part of the code. That would mean no milling is done, maybe we'll need to think about removing that sample from the list altogether.

```python-traceback
c:\Program Files\Python35\envs\AutoScript\lib\site-packages\skimage\measure\_moments.py:383: RuntimeWarning: invalid value encountered in true_divide
  / M[(0,) * image.ndim])  # weighted sum of all points
Traceback (most recent call last):
  File "fibsem/main.py", line 12, in <module>
    main(args)
  File "fibsem/main.py", line 5, in main
    samples = fibsem.sample.add_samples(microscope, args)
  File "c:\users\genevieb\documents\github\demarcolab\fibsem\fibsem\sample.py", line 86, in add_samples
    my_sample.orientation()
  File "c:\users\genevieb\documents\github\demarcolab\fibsem\fibsem\sample.py", line 71, in orientation
    self.mask, self.pixel_size)
  File "c:\users\genevieb\documents\github\demarcolab\fibsem\fibsem\orientation.py", line 121, in major_minor_axes_realspace
    major_axis_px, minor_axis_px = major_minor_axes_pixels(mask_image)
  File "c:\users\genevieb\documents\github\demarcolab\fibsem\fibsem\orientation.py", line 96, in major_minor_axes_pixels
    major_direction_vector = _orientation_vector(mask_image)
  File "c:\users\genevieb\documents\github\demarcolab\fibsem\fibsem\orientation.py", line 58, in _orientation_vector
    v, V = np.linalg.eig(T)
  File "c:\Program Files\Python35\envs\AutoScript\lib\site-packages\numpy\linalg\linalg.py", line 1128, in eig
    _assertFinite(a)
  File "c:\Program Files\Python35\envs\AutoScript\lib\site-packages\numpy\linalg\linalg.py", line 217, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.linalg.LinAlgError: Array must not contain infs or NaNs
```

**Comment by GenevieveBuckley** [comment]
https://github.com/DeMarcoLab/fibsem/pull/24
